export type KannadaLetter = {
  id: string;
  rank: number;     
  character: string;
  name: string;
  pronunciation: string;
  examples: string[];
  category: string;
  audio: string;
  word: string;
  image: string;
  transliteration: string;      
  exampleImages : string[]
};

export const kannadaAlphabet: KannadaLetter[] = [
  {
    id: "vowel-a",
    rank: 1,
    character: "ಅ",
    name: "a",
    pronunciation: "a as in 'america'",
    examples: ["ಅಪ್ಪ (appa) - father", "ಅಮ್ಮ (amma) - mother"],
    category: "vowel",
    audio: "/audio/1.mp3",
    word: 'ಅಪ್ಪ',
    image: '/images/words/1.jpg',
    transliteration: 'appa (father)',
    exampleImages : ['/images/words/1.jpg', '/images/words/2.jpg']
  },
  
  {
    id: "vowel-aa",
    rank: 2,
    character: "ಆ",
    name: "aa",
    pronunciation: "aa as in 'art'",
    examples: ["ಆನೆ (aane) - elephant", "ಆಕಾಶ (aakaasha) - sky"],
    category: "vowel",
    audio: "/audio/2.mp3",
    word: 'ಆನೆ',
    image: '/images/words/3.jpg',
    transliteration: 'aane (elephant)',
    exampleImages : ['/images/words/3.jpg', '/images/words/4.jpg']
  },
  {
    id: "vowel-i",
    rank: 3,
    character: "ಇ",
    name: "i",
    pronunciation: "i as in 'in'",
    examples: ["ಇಲಿ (ili) - rat", "ಇರುವೆ (iruve) - ant"],
    category: "vowel",
    audio: "/audio/3.mp3",
    word: 'ಇಲಿ',
    image: '/images/words/5.jpg',
    transliteration: 'ili (mouse)',
    exampleImages : ['/images/words/5.jpg', '/images/words/6.jpg']
  },
  {
    id: "vowel-ii",
    rank: 4,
    character: "ಈ",
    name: "ii",
    pronunciation: "ee as in 'eat'",
    examples: ["ಈಶ್ವರ (eeshwara) - god", "ಈರುಳ್ಳಿ (erulli) - Onion"],
    category: "vowel",
    audio: "/audio/4.mp3",
    word: 'ಈಶ್ವರ',
    image: '/images/words/7.jpg',
    transliteration: 'eeshwar (god)',
    exampleImages : ['/images/words/7.jpg', '/images/words/8.jpg']
  },
  {
    id: "vowel-u",
    rank: 5,
    character: "ಉ",
    name: "u",
    pronunciation: "u as in 'put'",
    examples: ["ಉಪ್ಪು (uppu) - salt", "ಉಡುಗೆ (uduge) - clothes"],
    category: "vowel",
    audio: "/audio/5.mp3",
    word: 'ಉಪ್ಪು',
    image: '/images/words/9.jpg',
    transliteration: 'uppu (soup)',
    exampleImages : ['/images/words/9.jpg', '/images/words/10.jpg']
  },
  {
    id: "vowel-uu",
    rank: 6,
    character: "ಊ",
    name: "uu",
    pronunciation: "oo as in 'food'",
    examples: ["ಊಟ (oota) - meal", "ಊರು (ooru) - village"],
    category: "vowel",
    audio: "/audio/6.mp3",
    word: 'ಊಟ',
    image: '/images/words/11.jpg',
    transliteration: 'oot (food)',
    exampleImages : ['/images/words/11.jpg', '/images/words/12.jpg']
  },
  {
    id: "vowel-ru",
    rank: 7,
    character: "ಋ",
    name: "ru",
    pronunciation: "ru as in 'ruby'",
    examples: ["ಋಷಿ (rushi) - sage", "ಋಷಭ (rushaba) - OX"],
    category: "vowel",
    audio: "/audio/7.mp3",
    word: 'ಋಷಿ',
    image: '/images/words/13.jpg',
    transliteration: 'rishi (teacher)',
    exampleImages : ['/images/words/13.jpg', '/images/words/14.jpg']
  },
  {
    id: "vowel-e",
    rank: 8,
    character: "ಎ",
    name: "e",
    pronunciation: "e as in 'egg'",
    examples: ["ಎಲೆ (ele) - leaf", "ಎರಡು (yeradu) - two"],
    category: "vowel",
    audio: "/audio/8.mp3",
    word: 'ಎಲೆ',
    image: '/images/words/15.jpg',
    transliteration: 'ele (leaf)',
    exampleImages : ['/images/words/15.jpg', '/images/words/16.jpg']
  },
  {
    id: "vowel-ee",
    rank: 9,
    character: "ಏ",
    name: "ee",
    pronunciation: "ay as in 'day'",
    examples: ["ಏಣಿ (eni) - ladder", "ಏಡಿ (yedi) - crab"],
    category: "vowel",
    audio: "/audio/9.mp3",
    word: 'ಏಣಿ',
    image: '/images/words/17.jpg',
    transliteration: 'ene (river)',
    exampleImages : ['/images/words/17.jpg', '/images/words/18.jpg']
  },
  {
    id: "vowel-ai",
    rank: 10,
    character: "ಐ",
    name: "ai",
    pronunciation: "ai as in 'aisle'",
    examples: ["ಐದು (aidu) - five", "ಐಸ್ (ais) - ice"],
    category: "vowel",
    audio: "/audio/10.mp3",
    word: 'ಐದು',
    image: '/images/words/19.jpg',
    transliteration: 'aidu (five)',
    exampleImages : ['/images/words/19.jpg', '/images/words/20.jpg']
  },
  {
    id: "vowel-o",
    rank: 11,
    character: "ಒ",
    name: "o",
    pronunciation: "o as in 'hot'",
    examples: ["ಒಂದು (ondu) - one", "ಒಂಟೆ (onte) - camel"],
    category: "vowel",
    audio: "/audio/11.mp3",
    word: 'ಒಂದು',
    image: '/images/words/21.jpg',
    transliteration: 'oondu (one)',
    exampleImages : ['/images/words/21.jpg', '/images/words/22.jpg']
  },
  {
    id: "vowel-oo",
    rank: 12,
    character: "ಓ",
    name: "oo",
    pronunciation: "o as in 'over'",
    examples: ["ಓದು (odu) - read", "ಓಟ (ota) - run"],
    category: "vowel",
    audio: "/audio/12.mp3",
    word: 'ಓದು',
    image: '/images/words/23.jpg',
    transliteration: 'oodu (read)',
    exampleImages : ['/images/words/23.jpg', '/images/words/24.jpg']
  },
  {
    id: "vowel-au",
    rank: 13,
    character: "ಔ",
    name: "au",
    pronunciation: "ou as in 'out'",
    examples: ["ಔಷಧ (aushadha) - medicine", "ಔದಾರ್ಯ (audarya) - generosity"],
    category: "vowel",
    audio: "/audio/13.mp3",
    word: 'ಔಷಧ',
    image: '/images/words/25.jpg',
    transliteration: 'aushadha (medicine)',
    exampleImages : ['/images/words/25.jpg', '/images/words/26.jpg']
  },
  
  {
    id: "vowel-am",
    rank: 14,
    character: "ಅಂ",
    name: "am",
    pronunciation: "am as in 'umbrella' (nasalized sound)",
    examples: ["ಹಂಸ (hamsa) - swan", "ಅಂಗಡಿ (angadi) - shop"],
    category: "vowel",
    audio: "/audio/14.mp3",
    word: 'ಹಂಸ',
    image: '/images/words/27.jpg',
    transliteration: 'hans (horse)',
    exampleImages : ['/images/words/27.jpg', '/images/words/28.jpg']
  },
  {
    id: "vowel-ahh",
    rank: 15,
    character: "ಅಃ",
    name: "ahh",
    pronunciation: "ahh as in 'aha!' (breathy sound)",
    examples: ["ನಮಃ (namah) - salutation", "ಶಾಂತಿಃ (shantih) - peace"],
    category: "vowel",
    audio: "/audio/15.mp3",
    word: 'ನಮಃ',
    image: '/images/words/29.jpg',
    transliteration: 'namah (salutation)',
    exampleImages : ['/images/words/29.jpg', '/images/words/30.jpg']
  },
  {
    id: "consonant-ka",
    rank: 16,
    character: "ಕ",
    name: "ka",
    pronunciation: "k as in 'kite'",
    examples: ["ಕರಡಿ  (Karadi) - Bear", "ಕಾಗೆ (kaage) - crow"],
    category: "consonant",
    audio: "/audio/16.mp3",
    word: 'ಕರಡಿ',
    image: '/images/words/31.jpg',
    transliteration: 'Karadi (Bear)',
    exampleImages: ['/images/words/31.jpg', '/images/words/32.jpg']
  },
  {
    id: "consonant-kha",
    rank: 17,
    character: "ಖ",
    name: "kha",
    pronunciation: "kh as in 'khaki'",
    examples: ["ಖಡ್ಗ (Khadga) - Sword", "ಖನಿಜ (khanija) - mineral"],
    category: "consonant",
    audio: "/audio/17.mp3",
    word: 'ಖಡ್ಗ',
    image: '/images/words/33.jpg',
    transliteration: 'Khadga (Sword)',
    exampleImages: ['/images/words/33.jpg', '/images/words/34.jpg']
  },
  {
    id: "consonant-ga",
    rank: 18,
    character: "ಗ",
    name: "ga",
    pronunciation: "g as in 'go'",
    examples: ["ಗಡಿಯಾರ (Gadiyaara) - Clock", "ಗಾಳಿ (gaali) - wind"],
    category: "consonant",
    audio: "/audio/18.mp3",
    word: 'ಗಡಿಯಾರ',
    image: '/images/words/35.jpg',
    transliteration: 'Gadiyaara (Clock)',
    exampleImages: ['/images/words/35.jpg', '/images/words/36.jpg']
  },
  {
    id: "consonant-gha",
    rank: 19,
    character: "ಘ",
    name: "gha",
    pronunciation: "gh as in 'ghost'",
    examples: ["ಘಂಟೆ (Ghante) - Bell", "ಘನತೆ (ghanate) - density"],
    category: "consonant",
    audio: "/audio/19.mp3",
    word: 'ಘಂಟೆ',
    image: '/images/words/37.jpg',
    transliteration: 'Ghante (Bell)',
    exampleImages: ['/images/words/37.jpg', '/images/words/38.jpg']
  },
  {
    id: "consonant-nga",
    rank: 20,
    character: "ಙ",
    name: "nga",
    pronunciation: "ng as in 'sing'",
    examples: ["ಮಂಗ (manga) - monkey", "ಅಂಗ (anga) - limb"],
    category: "consonant",
    audio: "/audio/20.mp3",
    word: 'ಮಂಗ',
    image: '/images/words/39.jpg',
    transliteration: 'manga (monkey)',
    exampleImages: ['/images/words/39.jpg', '/images/words/40.jpg']
  },
  {
    id: "consonant-cha",
    rank: 21,
    character: "ಚ",
    name: "cha",
    pronunciation: "ch as in 'chair'",
    examples: ["ಚಮಚ (chamacha) - spon", "ಚಿತ್ರ (chitra) - picture"],
    category: "consonant",
    audio: "/audio/21.mp3",
    word: 'ಚಮಚ',
    image: '/images/words/41.jpg',
    transliteration: 'chamacha (spon)',
    exampleImages: ['/images/words/41.jpg', '/images/words/42.jpg']
  },
  {
    id: "consonant-chha",
    rank: 22,
    character: "ಛ",
    name: "chha",
    pronunciation: "chh as in 'church-hill' (aspirated)",
    examples: ["ಛತ್ರಿ (chhatri) - umbrella", "ಛಾಯೆ (chhaaye) - shadow"],
    category: "consonant",
    audio: "/audio/22.mp3",
    word: 'ಛತ್ರಿ',
    image: '/images/words/43.jpg',
    transliteration: 'chhatri (umbrella)',
    exampleImages: ['/images/words/43.jpg', '/images/words/44.jpg']
  },
  {
    id: "consonant-ja",
    rank: 23,
    character: "ಜ",
    name: "ja",
    pronunciation: "j as in 'jump'",
    examples: ["ಜಹಾಜು  (Jahaju) - Ship ", "ಜನ (jana) - people"],
    category: "consonant",
    audio: "/audio/23.mp3",
    word: 'ಜಹಾಜು ',
    image: '/images/words/45.jpg',
    transliteration: 'Jahaju (Ship)',
    exampleImages: ['/images/words/45.jpg', '/images/words/46.jpg']
  },
  {
    id: "consonant-jha",
    rank: 24,
    character: "ಝ",
    name: "jha",
    pronunciation: "jh as in 'hedge-hog' (aspirated)",
    examples: ["ಝರಿ (jhari) - stream", "ಝಂಕಾರ (jhankaar) - jingle"],
    category: "consonant",
    audio: "/audio/24.mp3",
    word: 'ಝರಿ',
    image: '/images/words/47.jpg',
    transliteration: 'jhari (stream)',
    exampleImages: ['/images/words/47.jpg', '/images/words/48.jpg']
  },
  {
    id: "consonant-nya",
    rank: 25,
    character: "ಞ",
    name: "nya",
    pronunciation: "ny as in 'canyon'",
    examples: ["ಪಞ್ಚ (pancha) - five", "ಕಞ್ಚು (kanchu) - bronze"],
    category: "consonant",
    audio: "/audio/25.mp3",
    word: 'ಪಞ್ಚ',
    image: '/images/words/49.jpg',
    transliteration: 'pancha (five)',
    exampleImages: ['/images/words/49.jpg', '/images/words/50.jpg']
  },
  {
    id: "consonant-ta",
    rank: 26,
    character: "ಟ",
    name: "ta",
    pronunciation: "t as in 'top' (retroflex)",
    examples: ["ಟಗರು (Tagaru) - sheep", "ಪೆಟ್ಟಿಗೆ (pettige) - box"],
    category: "consonant",
    audio: "/audio/26.mp3",
    word: 'ಟಗರು',
    image: '/images/words/51.jpg',
    transliteration: 'sheep(Tagaru)',
    exampleImages: ['/images/words/51.jpg', '/images/words/52.jpg']
  },
  {
    id: "consonant-tha",
    rank: 27,
    character: "ಠ",
    name: "tha",
    pronunciation: "th as in 'thump' (retroflex, aspirated)",
    examples: ["ಠಾಣೆ (thaane) - police station", "ಕಠೋರ (kathora) - harsh"],
    category: "consonant",
    audio: "/audio/27.mp3",
    word: 'ಠಾಣೆ',
    image: '/images/words/53.jpg',
    transliteration: 'thaane (police station)',
    exampleImages: ['/images/words/53.jpg', '/images/words/54.jpg']
  },
  {
    id: "consonant-da",
    rank: 28,
    character: "ಡ",
    name: "da",
    pronunciation: "d as in 'dog' (retroflex)",
    examples: ["ಡಮರೂಗ (Damarugha) - Damaru)", "ಹುಡುಗ (huduga) - boy"],
    category: "consonant",
    audio: "/audio/28.mp3",
    word: 'ಡಮರೂಗ',
    image: '/images/words/55.jpg',
    transliteration: 'Damarugha (Damaru))',
    exampleImages: ['/images/words/55.jpg', '/images/words/56.jpg']
  },
  {
    id: "consonant-dha",
    rank: 29,
    character: "ಢ",
    name: "dha",
    pronunciation: "dh as in 'adhere' (retroflex, aspirated)",
    examples: ["ಢಾಕೆ (dhaake) - drum", "ಢಾಲು (dhaalu) - shield"],
    category: "consonant",
    audio: "/audio/29.mp3",
    word: 'ಢಾಕೆ',
    image: '/images/words/57.jpg',
    transliteration: 'dhaake (drum)',
    exampleImages: ['/images/words/57.jpg', '/images/words/58.jpg']
  },
  {
    id: "consonant-na",
    rank: 30,
    character: "ಣ",
    name: "na",
    pronunciation: "n as in 'under' (retroflex)",
    examples: ["ನಾಣ್ಯ (Nāṇya) - Coin", "ಕಾರಣ (kaarana) - reason"],
    category: "consonant",
    audio: "/audio/30.mp3",
    word: 'ನಾಣ್ಯ',
    image: '/images/words/59.jpg',
    transliteration: 'Nāṇya (Coin)',
    exampleImages: ['/images/words/59.jpg', '/images/words/60.jpg']
  },
  {
    id: "consonant-tha-dental",
    rank: 31,
    character: "ತ",
    name: "tha",
    pronunciation: "th as in 'thumb' (dental)",
    examples: ["ತಕಡಿ (Thakadi) - Weighing scaler", "ತಲೆ (tale) - head"],
    category: "consonant",
    audio: "/audio/31.mp3",
    word: 'ತಕಡಿ',
    image: '/images/words/61.jpg',
    transliteration: 'Thakadi (Weighing scale)',
    exampleImages: ['/images/words/61.jpg', '/images/words/62.jpg']
  },
  {
    id: "consonant-thha",
    rank: 32,
    character: "ಥ",
    name: "thha",
    pronunciation: "thh as in 'lighthouse' (dental, aspirated)",
    examples: ["ಥರ್ಮಾಮೀಟರ್ (Tāpamāpaka) - Thermometer", "ಪಥ (patha) - path"],
    category: "consonant",
    audio: "/audio/32.mp3",
    word: 'ಥರ್ಮಾಮೀಟರ್',
    image: '/images/words/63.jpg',
    transliteration: 'Tāpamāpaka (Thermometer)',
    exampleImages: ['/images/words/63.jpg', '/images/words/64.jpg']
  },
  {
    id: "consonant-da-dental",
    rank: 33,
    character: "ದ",
    name: "da",
    pronunciation: "d as in 'day' (dental)",
    examples: ["ದನ (dana) - cattle", "ದಿನ (dina) - day"],
    category: "consonant",
    audio: "/audio/33.mp3",
    word: 'ದನ',
    image: '/images/words/65.jpg',
    transliteration: 'dana(cattle)',
    exampleImages: ['/images/words/65.jpg', '/images/words/66.jpg']
  },
  {
    id: "consonant-dhha",
    rank: 34,
    character: "ಧ",
    name: "dhha",
    pronunciation: "dh as in 'dharma' (dental, aspirated)",
    examples: ["ಧನಸು (Dhanasu) - bow", "ಧೈರ್ಯ (dhairya) - courage"],
    category: "consonant",
    audio: "/audio/34.mp3",
    word: 'ಧನಸು',
    image: '/images/words/67.jpg',
    transliteration: 'Dhanasu (bow)',
    exampleImages: ['/images/words/67.jpg', '/images/words/68.jpg']
  },
  {
    id: "consonant-na-dental",
    rank: 35,
    character: "ನ",
    name: "na",
    pronunciation: "n as in 'name' (dental)",
    examples: ["ನವಿಲು ( Navilu ) - Peacock", "ನದಿ (nadi) - river"],
    category: "consonant",
    audio: "/audio/35.mp3",
    word: 'ನವಿಲು',
    image: '/images/words/69.jpg',
    transliteration: 'Navilu  (Peacock)',
    exampleImages: ['/images/words/69.jpg', '/images/words/70.jpg']
  },
  {
    id: "consonant-pa",
    rank: 36,
    character: "ಪ",
    name: "pa",
    pronunciation: "p as in 'pen'",
    examples: ["ಪಟ (paṭa) - Kite ", "ಪಕ್ಷಿ (pakshi) - bird"],
    category: "consonant",
    audio: "/audio/36.mp3",
    word: 'ಪಟ',
    image: '/images/words/71.jpg',
    transliteration: 'paṭa (Kite )',
    exampleImages: ['/images/words/71.jpg', '/images/words/72.jpg']
  },
  {
    id: "consonant-pha",
    rank: 37,
    character: "ಫ",
    name: "pha",
    pronunciation: "ph as in 'pharmacy' (aspirated)",
    examples: ["ಫಲ (phala) - fruit", "ಫುಲ್ (phul) - flower"],
    category: "consonant",
    audio: "/audio/37.mp3",
    word: 'ಫಲ',
    image: '/images/words/73.jpg',
    transliteration: 'phala (fruit)',
    exampleImages: ['/images/words/73.jpg', '/images/words/74.jpg']
  },
  {
    id: "consonant-ba",
    rank: 38,
    character: "ಬ",
    name: "ba",
    pronunciation: "b as in 'ball'",
    examples: ["ಬಂಗಾರ (bangara) - Gold", "ಭಾರತ (bhaarata) - India"],
    category: "consonant",
    audio: "/audio/38.mp3",
    word: 'ಬಂಗಾರ',
    image: '/images/words/75.jpg',
    transliteration: 'bangara (Gold)',
    exampleImages: ['/images/words/75.jpg', '/images/words/76.jpg']
  },
  {
    id: "consonant-bha",
    rank: 39,
    character: "ಭ",
    name: "bha",
    pronunciation: "bh as in 'abhor' (aspirated)",
    examples: ["ಭವನ (bhavana) -Palace", "ಭಾರತ (bhaarata) - India"],
    category: "consonant",
    audio: "/audio/39.mp3",
    word: 'ಭವನ',
    image: '/images/words/77.jpg',
    transliteration: 'bhavana (Palace)',
    exampleImages: ['/images/words/77.jpg', '/images/words/78.jpg']
  },
  {
    id: "consonant-ma",
    rank: 40,
    character: "ಮ",
    name: "ma",
    pronunciation: "m as in 'mother'",
    examples: ["ಮರ (Mara) - Tree", "ಮಗು (magu) - child"],
    category: "consonant",
    audio: "/audio/40.mp3",
    word: 'ಮರ',
    image: '/images/words/79.jpg',
    transliteration: 'Mara (Tree)',
    exampleImages: ['/images/words/79.jpg', '/images/words/80.jpg']
  },
  {
    id: "consonant-ya",
    rank: 41,
    character: "ಯ",
    name: "ya",
    pronunciation: "y as in 'yes'",
    examples: ["ಯಮ (yama) - Yama god", "ಯುದ್ಧ (yuddha) - war"],
    category: "consonant",
    audio: "/audio/41.mp3",
    word: 'ಯಮ',
    image: '/images/words/81.jpg',
    transliteration: 'yama (Yama god)',
    exampleImages: ['/images/words/81.jpg', '/images/words/82.jpg']
  },
  {
    id: "consonant-ra",
    rank: 42,
    character: "ರ",
    name: "ra",
    pronunciation: "r as in 'run'",
    examples: ["ರವಿ (ravi) - sun", "ರಾತ್ರಿ (raatri) - night"],
    category: "consonant",
    audio: "/audio/42.mp3",
    word: 'ರವಿ',
    image: '/images/words/83.jpg',
    transliteration: 'ravi (sun)',
    exampleImages: ['/images/words/83.jpg', '/images/words/84.jpg']
  },
  {
    id: "consonant-la",
    rank: 43,
    character: "ಲ",
    name: "la",
    pronunciation: "l as in 'lake'",
    examples: ["ಲಡು (lLadu) - Ladu sweet", "ಲೋಕ (loka) - world"],
    category: "consonant",
    audio: "/audio/43.mp3",
    word: 'ಲಡು',
    image: '/images/words/85.jpg',
    transliteration: 'Ladu (Ladu sweet)',
    exampleImages: ['/images/words/85.jpg', '/images/words/86.jpg']
  },
  {
    id: "consonant-va",
    rank: 44,
    character: "ವ",
    name: "va",
    pronunciation: "v as in 'van'",
    examples: ["ವಜ್ರ (Vajra) - Diamond", "ವಿದ್ಯೆ (vidye) - education"],
    category: "consonant",
    audio: "/audio/44.mp3",
    word: 'ವಜ್ರ',
    image: '/images/words/87.jpg',
    transliteration: 'Vajra (Diamond)',
    exampleImages: ['/images/words/87.jpg', '/images/words/88.jpg']
  },
  {
    id: "consonant-sha",
    rank: 45,
    character: "ಶ",
    name: "sha",
    pronunciation: "sh as in 'shine'",
    examples: ["ಶಂಕು (Shanku) - seashell", "ಶುಭ (shubha) - auspicious"],
    category: "consonant",
    audio: "/audio/45.mp3",
    word: 'ಶಂಕು',
    image: '/images/words/89.jpg',
    transliteration: 'Shanku (seashell)',
    exampleImages: ['/images/words/89.jpg', '/images/words/90.jpg']
  },
  {
    id: "consonant-sha-palatal",
    rank: 46,
    character: "ಷ",
    name: "sha",
    pronunciation: "sh as in 'shore' (retroflex)",
    examples: ["ಷಡ್ಚಕ್ರ (shadchakra) - six chakras", "ಪುಷ್ಪ (pushpa) - flower"],
    category: "consonant",
    audio: "/audio/46.mp3",
    word: 'ಪುಷ್ಪ',
    image: '/images/words/91.jpg',
    transliteration: 'pushpa (flower)',
    exampleImages: ['/images/words/91.jpg', '/images/words/92.jpg']
  },
  {
    id: "consonant-sa",
    rank: 47,
    character: "ಸ",
    name: "sa",
    pronunciation: "s as in 'sun'",
    examples: ["ಸಹನೆ (sahane) - patience", "ಸರೋವರ (sarovara) - lake"],
    category: "consonant",
    audio: "/audio/47.mp3",
    word: 'ಸಹನೆ',
    image: '/images/words/93.jpg',
    transliteration: 'sahane (patience)',
    exampleImages: ['/images/words/93.jpg', '/images/words/94.jpg']
  },
  {
    id: "consonant-ha",
    rank: 48,
    character: "ಹ",
    name: "ha",
    pronunciation: "h as in 'hat'",
    examples: ["ಹಕ್ಕಿ (hakki) - bird", "ಹಲ್ಲು (hallu) - tooth"],
    category: "consonant",
    audio: "/audio/48.mp3",
    word: 'ಹಕ್ಕಿ',
    image: '/images/words/95.jpg',
    transliteration: 'hakki (bird)',
    exampleImages: ['/images/words/95.jpg', '/images/words/96.jpg']
  },
  {
    id: "consonant-la-retroflex",
    rank: 49,
    character: "ಳ",
    name: "la",
    pronunciation: "l as in 'curl' (retroflex)",
    examples: ["ಹುಳ (hula) - worm", "ಬೆಳೆ (bele) - crop"],
    category: "consonant",
    audio: "/audio/49.mp3",
    word: 'ಹುಳ',
    image: '/images/words/97.jpg',
    transliteration: 'hula (worm)',
    exampleImages: ['/images/words/97.jpg', '/images/words/98.jpg']
  }
];

export default kannadaAlphabet;